---
apiVersion: v1
kind: Service
metadata:
  name: python-addy-svc
  namespace: barryns
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: python-addy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-addy-agic-ig
  namespace: barryns
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-addy-svc
            port:
              number: 80