kind: Service
apiVersion: v1
metadata:
  name: python-addy
  namespace: barryns
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: python-addy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web